import argparse
import hashlib
from pathlib import Path
from typing import Iterable


OLD_HASH = b"c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6"
SUKISU_HASH = b"947ae944f3de4ed4c21a7e4f7953ecf351bfa2b36239da37a34111ad29993eef"
KOWX_HASH = b"484fcba6e6c43b1fb09700633bf2fb4758f13cb0b2f4457b80d075084b26c588"
EPKESU_NEW_HASH = b"94568040da597f3f2c44be6c5b5b52fbd563985669b9074f28b21813aa229cc6"
TARGET_HASH = b"1c89980c03432844cfe195dab90bfaecbcd987d19309da648014164be78007d1"

# AArch64 encodings generated by Clang for EXPECTED_SIZE in is_manager_apk.
OLD_CMP_SIZE = bytes.fromhex("1fed0c71")  # cmp w8, #0x33b
EPKESU_NEW_CMP_SIZE = bytes.fromhex("1fe90d71")  # cmp w8, #0x37a
TARGET_CMP_SIZE = bytes.fromhex("1fa10b71")  # cmp w8, #0x2e8
OLD_MOV_SIZE = bytes.fromhex("62678052")  # mov w2, #0x33b
EPKESU_NEW_MOV_SIZE = bytes.fromhex("426f8052")  # mov w2, #0x37a
TARGET_MOV_SIZE = bytes.fromhex("025d8052")  # mov w2, #0x2e8

# SukiSU-Ultra v4.1.3 release LKMs use their own manager certificate.
SUKISU_CMP_SIZE = bytes.fromhex("1f710d71")  # cmp w8, #0x35c
SUKISU_MOV_SIZE = bytes.fromhex("826b8052")  # mov w2, #0x35c

# KOWX712/KernelSU action LKMs use their own manager certificate.
KOWX_CMP_SIZE = bytes.fromhex("1fd50d71")  # cmp w8, #0x375
KOWX_MOV_SIZE = bytes.fromhex("a26e8052")  # mov w2, #0x375


def replace_once(data: bytes, old: bytes, new: bytes, label: str, path: Path) -> bytes:
    count = data.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected one {label}, found {count}")
    return data.replace(old, new, 1)


def patch_file(path: Path) -> None:
    before = path.read_bytes()
    data = before
    variants = [
        ("KernelSU", OLD_HASH, OLD_CMP_SIZE, OLD_MOV_SIZE),
        ("SukiSU", SUKISU_HASH, SUKISU_CMP_SIZE, SUKISU_MOV_SIZE),
        ("KOWX712", KOWX_HASH, KOWX_CMP_SIZE, KOWX_MOV_SIZE),
        ("EpkeSU-new", EPKESU_NEW_HASH, EPKESU_NEW_CMP_SIZE, EPKESU_NEW_MOV_SIZE),
    ]
    matches = [
        variant
        for variant in variants
        if data.count(variant[1]) == 1
    ]
    if not matches and data.count(TARGET_HASH) == 1:
        print(f"already patched {path}")
        return
    if len(matches) != 1:
        labels = ", ".join(label for label, _, _, _ in variants)
        raise RuntimeError(f"{path}: expected exactly one known manager hash variant ({labels}), found {len(matches)}")

    label, old_hash, old_cmp_size, old_mov_size = matches[0]
    data = replace_once(data, old_hash, TARGET_HASH, f"{label} manager hash", path)
    data = replace_once(data, old_cmp_size, TARGET_CMP_SIZE, f"{label} certificate size compare", path)
    data = replace_once(data, old_mov_size, TARGET_MOV_SIZE, f"{label} certificate size read", path)

    if len(data) != len(before):
        raise RuntimeError(f"{path}: patched file size changed")

    path.write_bytes(data)
    digest = hashlib.sha256(data).hexdigest()
    print(f"patched {path} sha256={digest}")


def iter_targets(values: Iterable[str]) -> Iterable[Path]:
    for value in values:
        path = Path(value)
        if path.is_dir():
            yield from sorted(path.glob("*_kernelsu.ko"))
        else:
            yield path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Patch bundled KernelSU LKM manager identity for the EpkeSU release key."
    )
    parser.add_argument("targets", nargs="+", help="LKM .ko file or directory")
    args = parser.parse_args()

    for target in iter_targets(args.targets):
        patch_file(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
